[2023-10-22T10:03:19.481+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_day18.transform_data_api manual__2023-10-22T10:03:11.695063+00:00 [queued]>
[2023-10-22T10:03:19.492+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_day18.transform_data_api manual__2023-10-22T10:03:11.695063+00:00 [queued]>
[2023-10-22T10:03:19.493+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T10:03:19.506+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_data_api> on 2023-10-22 10:03:11.695063+00:00
[2023-10-22T10:03:19.512+0000] {standard_task_runner.py:57} INFO - Started process 2144 to run task
[2023-10-22T10:03:19.515+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_day18', 'transform_data_api', 'manual__2023-10-22T10:03:11.695063+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/ETL_day18.py', '--cfg-path', '/tmp/tmpk71yk8u4']
[2023-10-22T10:03:19.519+0000] {standard_task_runner.py:85} INFO - Job 255: Subtask transform_data_api
[2023-10-22T10:03:19.570+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_day18.transform_data_api manual__2023-10-22T10:03:11.695063+00:00 [running]> on host 90cf752d844d
[2023-10-22T10:03:19.838+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel11' AIRFLOW_CTX_DAG_ID='etl_day18' AIRFLOW_CTX_TASK_ID='transform_data_api' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T10:03:11.695063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T10:03:11.695063+00:00'
[2023-10-22T10:03:19.890+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-22T10:03:19.902+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=etl_day18, task_id=transform_data_api, execution_date=20231022T100311, start_date=20231022T100319, end_date=20231022T100319
[2023-10-22T10:03:19.944+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-22T10:03:19.987+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
